ASSUME CS:CODE
ASSUME DS:DATA

DATA SEGMENT
ARR DB 01H,02H,03H,04H,05H
RES DB ?
DATA ENDS

CODE SEGMENT
START:MOV AX,DATA
      MOV DS,AX
      MOV AX,0000H

      LEA SI,ARR
      MOV BL,02H
      MOV CL,04H
      MOV DL,00H
  LOG:MOV AL,[SI]
      DIV BL      ;DIVIDING BECAUSE IF THE NUMBER IS EVEN IT WILL STORE 00 IN AH OR 01 IF ODD
      CMP AH,00H  ;IF AH IS ZERO THEN IT WILL JUMP TO UP LABEL
      JE UP
      INC SI
      LOOP LOG
      JMP EXIT
   UP:INC DL      ;INCREMENT DL BECAUSE THE NUMBER IS EVEN
      INC SI
      LOOP LOG
 EXIT:MOV RES,DL  ;STORING THE VALUE OF DL IN RES
      INT 03H     ;SHOCASING VALUE IN GREEN SCREEN
CODE ENDS
